trigger:
- main

stages:
  - stage: "BuildStage"
    jobs:
    - job: "Buildjob"
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js'

      - task: Npm@1
        displayName: "Npm install for client"
        inputs:
          command: 'install'
          workingDir: 'client'

      - task: Npm@1
        displayName: "Npm build for client"
        inputs:
          command: 'custom'
          workingDir: 'client'
          customCommand: 'run build'

      # - task: CopyFiles@2
      #   inputs:
      #     Contents: |
      #       client/build/**
      #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: ArchiveFiles@2
        displayName: 'Archive React Build'
        inputs:
          rootFolderOrFile: 'client/build'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
          replaceExistingArchive: true

      - publish: '$(Build.ArtifactStagingDirectory)/frontend.zip'
        artifact: 'drop'

  - stage: "DeployStage"
    dependsOn: "BuildStage"
    jobs:
    - job: 
      pool:
        vmImage: ubuntu-latest
      steps:
      - download: current
        artifact: drop

      - task: AzureRmWebAppDeployment@5
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Azure for Students(3726fb87-ee7b-42c4-a39c-d437513f686c)'
          appType: 'webAppLinux'
          WebAppName: 'project02Student'
          packageForLinux: '$(Pipeline.Workspace)/drop/frontend.zip'
          DeploymentTypeLinux: 'zipDeploy'
          StartupCommand: 'cd client && npm start'