trigger:
- main

stages:
  - stage: BuildStage
    jobs:
    - job: BuildJob
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js'

      - task: Npm@1
        displayName: 'Install Dependencies'
        inputs:
          command: 'install'
          workingDir: 'client'

      - task: Npm@1
        displayName: 'Build React App'
        inputs:
          command: 'custom'
          workingDir: 'client'
          customCommand: 'run build'

      - task: ArchiveFiles@2
        displayName: 'Archive React Build'
        inputs:
          rootFolderOrFile: 'client/build'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'drop'
          publishLocation: 'pipeline'
      - script: |
          echo "Pipeline.Workspace path:"
          echo "$(Pipeline.Workspace)"
          echo "Listing contents of $(Pipeline.Workspace)/drop:"
          ls -la $(Pipeline.Workspace)/drop
        displayName: 'Verify artifact location'


  - stage: DeployStage
    dependsOn: BuildStage
    jobs:
    - job: DeployJob
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'drop'
          targetPath: '$(Pipeline.Workspace)'

      - task: AzureRmWebAppDeployment@5
        displayName: 'Deploy React App to Azure'
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Azure for Students(3726fb87-ee7b-42c4-a39c-d437513f686c)'
          appType: 'webAppLinux'
          WebAppName: 'project01Student'
          packageForLinux: '$(System.ArtifactsDirectory)/drop/frontend.zip'

          DeploymentTypeLinux: 'zipDeploy'
